In [1]:
import numpy as np

In [2]:
cly = [1,1,1,0,0,0]
edi = [1,1,1,1,0,0]
lpl = [1,1,1,1,1,0]
yor = [0,1,1,1,1,1]
wal = [0,0,1,1,1,1]
lon = [0,0,0,1,1,1]

connections = np.array([cly, edi, lpl, yor, wal, lon])

In [3]:
army_cly = [0,0,0]
army_edi = [1,0,0]
army_lpl = [0,1,0]
army_yor = [0,0,0]
army_wal = [0,0,0]
army_lon = [0,0,1]

army_location = np.array([army_cly, army_edi, army_lpl, army_yor, army_wal, army_lon])

In [4]:
army_location

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [5]:
_edi = [1,0,0]
_lpl = [0,1,0]
_lon = [0,0,1]

supply_control = np.array([_edi, _lpl, _lon])

In [6]:
connections, army_location, supply_control

(array([[1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 0],
        [0, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1]]), array([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]]), array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]))

In [7]:
def get_move(country, order):
    """ num_countries * orders (actions)
    row = country
    col 0 = move (moving, holding, attacking)
    col 1 = support defender
    col 2 = support attacker
    
    TODO: need to add support for players rather than support for location
     - maybe try 18 length vector: 6 to move, 6 location from,6 location too
    """
    move_array = np.array([[0]*3]*6)
    move_array[country, order] = 1
    return move_array

In [31]:
get_move(3, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
def make_move(player, move, connections, army_location, supply_control):
    """ A move means moving the army.
    player: for form [0,0,1] means third player
    move: specified in get_move
    connections: board constant
    army_location: num_countries * num_players. One hot encoding for player army in country
    supply_control: num_supply_centres * num_players. One hot encoding for player army in country. 
                    Only updated when player moves through
    return army_location and supply_control
    """
    
    index = np.argmax(player)
    move_country = max(np.argmax(move, axis=0))
    move_type = max(np.argmax(move, axis=1))
    print(index, move_country, move_type)
    if connections[move_country, index]:
        print("valid")
    else:
        print("not valid")
        
    
    
    return army_location, supply_control
    

In [53]:
move = get_move(5, 0)
make_move([0,0,2], move, connections, army_location, supply_control)

2 5 0
not valid


(array([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]]), array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]))

In [54]:
connections

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])